# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoMetrics
                                 A QGIS plugin
 Counts the ammount of certain geometries on each layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-11
        copyright            : (C) 2024 by Kavest0 | Kayo
        email                : felipebrkr@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoMetrics class from file GeoMetrics.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GeoMetrics import GeoMetrics
    return GeoMetrics(iface)
